name: Daily Auto Checkout

on:
  schedule:
    # 12:00 PM IST = 6:30 AM UTC
    - cron: "20 06 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger ASPX Auto Checkout
        run: |
          curl -I "http://accsoftacademy-002-site3.ktempurl.com" \
               -H "User-Agent: GitHubCron"
