name: Daily Auto Checkout

on:
  schedule:
    # 12:00 PM IST = 6:30 AM UTC
    - cron: "42 19 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger ASPX Auto Checkout
        run: |
          curl -I "https://unpatronisable-handsomeish-alita.ngrok-free.dev/AutoCheckout.aspx" \
               -H "ngrok-skip-browser-warning: true" \
               -H "User-Agent: GitHubCron"
